### ISSUE TITLE
Direct Link about article contains an unfilled variable reference 

### ISSUE THREAD

**Issue by aerwin** [ibm-cloud-docs/dl#15]
On the Direct Link about article (see https://cloud.ibm.com/docs/dl?topic=dl-dl-about), there is an unfilled variable reference that should be corrected.

![image](https://user-images.githubusercontent.com/1258743/88930480-27c2b380-d241-11ea-91ba-e949c5fe6c70.png)

**Comment by austinmama** [comment]
@aerwin  Thank you, Tony.  Fixed!
