### ISSUE TITLE
Missing steps in the configuration of the Direct Link Connect.....

### ISSUE THREAD

**Issue by LarsIpsen** [ibm-cloud-docs/dl#16]
My client follow the steps and they are sufficient.
We don't inform that you need to create a route in the VPC route table, before the connection works. The XCR will not advertise the route to the VPC, and therefore the client must update the route table. 
It has been a support case, you can see the answer from the Support team here: https://ibm-cloudplatform.slack.com/archives/CS62UR3RD/p1607201007115500

**Comment by austinmama** [comment]
@LarsIpsen   Thank you for your feedback.  I updated both the FAQ and VRF topics to state:


_When routing on-premises subnets from the direct link through a VPC, you must create a route in the VPC routing table. For more information, see Creating a route._

https://cloud.ibm.com/docs/dl?topic=dl-faqs#connect-wo-using-classic
https://cloud.ibm.com/docs/dl?topic=dl-overview-of-virtual-routing-and-forwarding-vrf-on-ibm-cloud#routing-considerations-vpc

**Comment by LarsIpsen** [comment]
Thx 
My point was not to route through the VPC, but just route from the VPC and through the DL(that is connected to the VPC) to the on-prems.
I have to admit, that I don't understand it should be necessary, but the IBM Cloud support team has told me, that it is, and my client can't get his DL to work unless he create the routes in VPC back to his on-prems network. So I assume that it is a necessary step, but it hard to find in the documentation. 
I read the link you provided, as a step, if I want to route through the VPC to something outside the VPC (but not back to his on-prems) 
 
Med venlig hilsen 
 
Lars Kjær Ipsen
Cloud  Architect
IBM Public Cloud
Prøvensvej 1, DK-2605 Brøndbyvester,Mobile: +45 4120 7301
e-mail: ipsen@dk.ibm.com
@ipsenlars
 
 
 
----- Original message -----From: austinmama <notifications@github.com>To: ibm-cloud-docs/dl <dl@noreply.github.com>Cc: "Lars Kjær Ipsen" <ipsen@dk.ibm.com>, Mention <mention@noreply.github.com>Subject: [EXTERNAL] Re: [ibm-cloud-docs/dl] Missing steps in the configuration of the Direct Link Connect..... (#16)Date: Mon, Dec 7, 2020 18:48 
 
@LarsIpsen Thank you for your feedback. I updated both the FAQ and VRF topics to state:
When routing on-premises subnets from the direct link through a VPC, you must create a route in the VPC routing table. For more information, see Creating a route.
https://cloud.ibm.com/docs/dl?topic=dl-faqs#connect-wo-using-classichttps://cloud.ibm.com/docs/dl?topic=dl-overview-of-virtual-routing-and-forwarding-vrf-on-ibm-cloud#routing-considerations-vpc
—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.
 Medmindre andet er angivet ovenfor: / Unless Otherwise Stated Above:
IBM Danmark ApS
Prøvensvej 1
2605 Brøndby, Danmark
CVR nr.: 65305216
