### ISSUE TITLE
IBM DirectLink 2.0 Dedicated not supported (as of 03/17/2021 by Equinix) due port access vs. trunk requirements

### ISSUE THREAD

**Issue by PrinceOfPoly** [ibm-cloud-docs/dl#17]
IBM DirectLink 2.0 Dedicated is not supported (as of 03/17/2021 by Equinix) due port access vs. trunk requirements.   The table below in the documentation is misleading as Equinix is listed, where they currently do not support IBM DirectLink 2.0 Dedicated.

**Comment by austinmama** [comment]
@PrinceOfPoly  Thank you for your feedback.  Are you referring to this page? [https://cloud.ibm.com/docs/dl?topic=dl-how-to-order-ibm-cloud-dl-dedicated#dedicated-locations](url)

**Comment by austinmama** [comment]
Per Development, Equinix still supports DL2.0 Dedicated in many locations.  Is this an error on a specific page?  If so, please reopen this issue and provide the URL. Thank you for your feedback.
