### ISSUE TITLE
Please insert a table that lists the valid combinations (dependencies)

### ISSUE THREAD

**Issue by tschrenk-corp** [ibm-cloud-docs/dl#21]
During network onboarding and the naming of the data centers creates a great confusion in combination with PowerVS -> DL -> Classic

I would love a table that lists the valid combinations like in the attachment.

This would avoid misconfigs like DL to FRANKFURT4 and Power Service in FRANKFURT2 which would mix eu-de1 and eu-de2.

[Valid Configs IBM Cloud1.1.xlsx](https://github.com/ibm-cloud-docs/dl/files/6717653/Valid.Configs.IBM.Cloud1.1.xlsx)

Thanks so much
Thomas

**Comment by austinmama** [comment]
This is very specific to PowerVS situation.

As far as DL is concern, we have list of available sites as PER IBM DC/POP regions:

https://cloud.ibm.com/docs/dl?topic=dl-locations#connect-locations
https://cloud.ibm.com/docs/overview?topic=overview-locations

PowerNS has Automation, listed at:
https://cloud.ibm.com/docs/power-iaas?topic=power-iaas-creating-power-virtual-server
