### ISSUE TITLE
Direct Link prerequisites should mention VRF Migration required

### ISSUE THREAD

**Issue by xdansmith** [ibm-cloud-docs/dl#25]
Re: https://cloud.ibm.com/docs/dl?topic=dl-ibm-cloud-dl-prerequisites

Article doesn't make it obvious that you must migrate your account to VRF before you can enable a Direct Link for Classic virtual connection. 

This can lead customers to order Direct Link not realizing they will need to have their classic account migrated which according to docs, can cause 15-30 minutes of packet loss.

**Comment by austinmama** [comment]
Step 8 was updated a few months back.  Thank you for your feedback.

https://cloud.ibm.com/docs/dl?topic=dl-ibm-cloud-dl-prerequisites
