### ISSUE TITLE
Please add to the FAQ comments about ability to use customer provided VLANID for DL 2.0 connect

### ISSUE THREAD

**Issue by notras** [ibm-cloud-docs/dl#26]
Can client/NNI to request IBM to change VLANID on IBM Cloud for provisioned DL 2.0 Connect with already allocated VLAN?

Answer - statement like this:
VLAN number for DL2.0 Connect GW allocated after ordering on IBM Cloud Portal can not be changed upon client request.
VLAN allocation performed in fully automated mode.

It can offload IBM Cloud  NW support team and help clients to reference to this statement with ISP provider cases.

**Comment by austinmama** [comment]
FAQs were reviewed with Development and provided at the following URLs:

https://cloud.ibm.com/docs/direct-link?topic=direct-link-faqs#change-vlan
https://cloud.ibm.com/docs/dl?topic=dl-faqs#change-vlan-id
