### ISSUE TITLE
Madrid Operator Site Code seems wrong - Direct Link Dedicated locations

### ISSUE THREAD

**Issue by bbushvt** [ibm-cloud-docs/dl#29]
I'm trying to get addresses for POP locations for a customer and the Madrid operator site codes seem wrong (Digital Reality doesn't seem to have a MAD03, just MAD02, MAD04, and MAD05 with IBM in them).
![image](https://github.com/ibm-cloud-docs/dl/assets/1264513/d4282d5d-5a78-4f32-9d01-ede89028a5b5)

Can these be verified?

**Comment by kanguyen7** [comment]
Here are the following addresses for Madrid:

MAD01 // Equinix Site Code: MD2 // POP
International Business Machine SA  - MAD01
c/o Equinix MD2
Calle Valgrande, 6
28108 Alcobendas, Madrid
Spain
------

MAD02 // DATA4 (not sure about the site code) // Data Center
Madrid, Spain - MAD02 - DATA4 Madrid Campus
International Business Machines SA
Av. de la Industria, 15
28108 Alcobendas, Madrid, Spain
------

MAD03 // InterXion (Digital Realty Company) Site Code: MAD3 // POP
International Business Machine SA  - MAD03
c/o Interxion MAD3
49 Calle Emilio Munoz
28037 Madrid
Spain
------

MAD04 // NTT Site Code MAD1 // Data Center
Madrid, Spain - MAD04 - NTT Data Center (MAD1)
International Business Machines SA
C. Aquisgrán, 2
28232 Las Rozas de Madrid, Madrid, Spain
------

MAD05 // InterXion (Digital Realty Company) Site Code MAD4 // Data Center
Madrid, Spain - MAD05 - Interxion (MAD4)
International Business Machines SA
C. de Alfonso Gómez, 6
28037 Madrid, Spain
