### ISSUE TITLE
Outdated Direct Link IAM configuration page

### ISSUE THREAD

**Issue by guildevi** [ibm-cloud-docs/dl#31]
Documentation chapter [Managing IAM access for IBM Cloud Direct Link](https://cloud.ibm.com/docs/dl?topic=dl-iam&interface=ui) only refers to gateway to configure IAM when IAM configuration contains Direct Link service and 5 different roles. Please review and update the documentation?

**Comment by austinmama** [comment]
Thank you for your feedback!  Subject matter expert reviewed this topic.  Updated version here: https://cloud.ibm.com/docs/dl?topic=dl-iam&interface=ui
