### ISSUE TITLE
DL Known Limitations URL mis-labeled 

### ISSUE THREAD

**Issue by tooloudcajun** [ibm-cloud-docs/dl#32]
### Which topic are you reporting about?

https://cloud.ibm.com/docs/dl?topic=dl-known-limitations&interface=ui

### What do you think needs to be updated?

First bullet - URL reads "VPN" and should read "VPC" for the link description.

VPC networking doesn't consider the AS path length when selecting the best route for network traffic. Therefore, AS prepends configured on direct links have no effect when VPCs are directly connected. However, you can use a transit gateway between the direct link and VPC in some topologies to achieve the wanted effect. For planning considerations, see [Using AS prepends with **VPN** connections](https://cloud.ibm.com/docs/dl?topic=dl-dl-planning-considerations&interface=ui#as-prepends-routes).

**Comment by austinmama** [comment]
Thank you for reporting this.  Fixing the error now!  Appreciate your help.
